//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sanatorium.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sanatorium
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Pics { get; set; }
        public string Description { get; set; }
        public string ShiShiOrg { get; set; }
        public string ShiGongOrg { get; set; }
        public Nullable<System.DateTime> PredictFinishTime { get; set; }
        public float StructureArea { get; set; }
        public float FinishArea { get; set; }
        public float DoingArea { get; set; }
        public float ToDoArea { get; set; }
        public string CompletionYear { get; set; }
        public int BuildingsCount { get; set; }
        public int StagingCount { get; set; }
        public string ShiGongScope { get; set; }
        public string ShiGongContent { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public string BuildOrg { get; set; }
        public string BuildOrgPrincipal { get; set; }
        public string BuildOrgPhone { get; set; }
        public string BuildOrgWeb { get; set; }
        public string DesignOrg { get; set; }
        public string DesignOrgPrincipal { get; set; }
        public string DesignOrgPhone { get; set; }
        public string DesignOrgWeb { get; set; }
        public string SupervisionOrg { get; set; }
        public string SupervisionOrgPrincipal { get; set; }
        public string SupervisionOrgPhone { get; set; }
        public string SupervisionOrgWeb { get; set; }
        public string Remark { get; set; }
        public string GongZiPhone { get; set; }
        public string JuMinPhone { get; set; }
        public string AnQuanZhiDu { get; set; }
        public string ShiGongZhidu { get; set; }
        public string XiaoFangZhidu { get; set; }
        public string ZhiAnPrincipal { get; set; }
        public string ZhiAnPrincipalPhone { get; set; }
        public string ZhiAnMembers { get; set; }
        public string XiaoFangPrincipal { get; set; }
        public string XiaoFangPrincipalPhone { get; set; }
        public string XiaoFangMembers { get; set; }
        public string YingJiPrincipal { get; set; }
        public string YingJiPrincipalPhone { get; set; }
        public string YingJiMembers { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string Region { get; set; }
        public string Street { get; set; }
        public string Community { get; set; }
    }
}
